// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWyHAL9kxCzaXIzCSi4SND3p2mNiRwM78',
    appId: '1:275288813880:web:0a6aade2a86011a26751cd',
    messagingSenderId: '275288813880',
    projectId: 'ndfire-4ea00',
    authDomain: 'ndfire-4ea00.firebaseapp.com',
    storageBucket: 'ndfire-4ea00.firebasestorage.app',
    measurementId: 'G-EK7MYE8VR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7A4re_ZPW-BUsDt9lyd45PG985Hrk3I',
    appId: '1:275288813880:android:43d55d03c9a9142c6751cd',
    messagingSenderId: '275288813880',
    projectId: 'ndfire-4ea00',
    storageBucket: 'ndfire-4ea00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2eFPIPCeYE7cRgvnYbTZIJLucZuMEEc',
    appId: '1:275288813880:ios:66054f7b2c3cb17a6751cd',
    messagingSenderId: '275288813880',
    projectId: 'ndfire-4ea00',
    storageBucket: 'ndfire-4ea00.firebasestorage.app',
    iosBundleId: 'com.example.multilinguilal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2eFPIPCeYE7cRgvnYbTZIJLucZuMEEc',
    appId: '1:275288813880:ios:66054f7b2c3cb17a6751cd',
    messagingSenderId: '275288813880',
    projectId: 'ndfire-4ea00',
    storageBucket: 'ndfire-4ea00.firebasestorage.app',
    iosBundleId: 'com.example.multilinguilal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWyHAL9kxCzaXIzCSi4SND3p2mNiRwM78',
    appId: '1:275288813880:web:7f571ef69cce55aa6751cd',
    messagingSenderId: '275288813880',
    projectId: 'ndfire-4ea00',
    authDomain: 'ndfire-4ea00.firebaseapp.com',
    storageBucket: 'ndfire-4ea00.firebasestorage.app',
    measurementId: 'G-E4QNY774F5',
  );
}
